import type { SepoliaContractName, SepoliaWorkflowRole } from "./sepolia-workflow-config.js";

export const RETAINED_SEPOLIA_WORKFLOW_SOURCE_REVISION = "2346f02a638921bcfd4418960450b91aff9f3ffa";

export type SepoliaWorkflowValueRule = "zero" | "purchase-amount";

export interface SepoliaWorkflowRecipeEntry {
  readonly sequence: number;
  readonly step: string;
  readonly contract: SepoliaContractName;
  readonly function: string;
  readonly signerRole: SepoliaWorkflowRole;
  readonly expectedEvents: readonly string[];
  readonly valueRule: SepoliaWorkflowValueRule;
}

function freezeWorkflowRecipe<const T extends readonly SepoliaWorkflowRecipeEntry[]>(
  recipe: T,
): Readonly<T> {
  for (const entry of recipe) {
    Object.freeze(entry.expectedEvents);
    Object.freeze(entry);
  }
  return Object.freeze(recipe);
}

export const sepoliaWorkflowRecipe = freezeWorkflowRecipe([
  {
    sequence: 1,
    step: "Activate evidence issuer organization",
    contract: "AuthorityProfileRegistry",
    function: "setOrganizationStatus",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.OrganizationStatusChanged"],
    valueRule: "zero",
  },
  {
    sequence: 2,
    step: "Register evidence issuer credential",
    contract: "AuthorityProfileRegistry",
    function: "setCredential",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.CredentialSet"],
    valueRule: "zero",
  },
  {
    sequence: 3,
    step: "Activate protected-record controller organization",
    contract: "AuthorityProfileRegistry",
    function: "setOrganizationStatus",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.OrganizationStatusChanged"],
    valueRule: "zero",
  },
  {
    sequence: 4,
    step: "Register protected-record controller credential",
    contract: "AuthorityProfileRegistry",
    function: "setCredential",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.CredentialSet"],
    valueRule: "zero",
  },
  {
    sequence: 5,
    step: "Activate independent verifier organization",
    contract: "AuthorityProfileRegistry",
    function: "setOrganizationStatus",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.OrganizationStatusChanged"],
    valueRule: "zero",
  },
  {
    sequence: 6,
    step: "Register independent verifier credential",
    contract: "AuthorityProfileRegistry",
    function: "setCredential",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.CredentialSet"],
    valueRule: "zero",
  },
  {
    sequence: 7,
    step: "Activate seller organization",
    contract: "AuthorityProfileRegistry",
    function: "setOrganizationStatus",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.OrganizationStatusChanged"],
    valueRule: "zero",
  },
  {
    sequence: 8,
    step: "Register seller credential",
    contract: "AuthorityProfileRegistry",
    function: "setCredential",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.CredentialSet"],
    valueRule: "zero",
  },
  {
    sequence: 9,
    step: "Activate buyer organization",
    contract: "AuthorityProfileRegistry",
    function: "setOrganizationStatus",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.OrganizationStatusChanged"],
    valueRule: "zero",
  },
  {
    sequence: 10,
    step: "Register buyer credential",
    contract: "AuthorityProfileRegistry",
    function: "setCredential",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.CredentialSet"],
    valueRule: "zero",
  },
  {
    sequence: 11,
    step: "Activate replica attester organization",
    contract: "AuthorityProfileRegistry",
    function: "setOrganizationStatus",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.OrganizationStatusChanged"],
    valueRule: "zero",
  },
  {
    sequence: 12,
    step: "Register replica attester credential",
    contract: "AuthorityProfileRegistry",
    function: "setCredential",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.CredentialSet"],
    valueRule: "zero",
  },
  {
    sequence: 13,
    step: "Activate logistics provider organization",
    contract: "AuthorityProfileRegistry",
    function: "setOrganizationStatus",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.OrganizationStatusChanged"],
    valueRule: "zero",
  },
  {
    sequence: 14,
    step: "Register logistics provider credential",
    contract: "AuthorityProfileRegistry",
    function: "setCredential",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.CredentialSet"],
    valueRule: "zero",
  },
  {
    sequence: 15,
    step: "Activate audit-anchor service organization",
    contract: "AuthorityProfileRegistry",
    function: "setOrganizationStatus",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.OrganizationStatusChanged"],
    valueRule: "zero",
  },
  {
    sequence: 16,
    step: "Register audit-anchor service credential",
    contract: "AuthorityProfileRegistry",
    function: "setCredential",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.CredentialSet"],
    valueRule: "zero",
  },
  {
    sequence: 17,
    step: "Authorize the battery registrar",
    contract: "BatteryOwnershipRegistry",
    function: "setRegistrar",
    signerRole: "governance",
    expectedEvents: [],
    valueRule: "zero",
  },
  {
    sequence: 18,
    step: "Approve the neutral replica repository",
    contract: "AuthorityProfileRegistry",
    function: "setRepositoryApproval",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.RepositoryApprovalChanged"],
    valueRule: "zero",
  },
  {
    sequence: 19,
    step: "Allow evidence issuance",
    contract: "AuthorityProfileRegistry",
    function: "setCapabilityGrant",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.CapabilityGrantSet"],
    valueRule: "zero",
  },
  {
    sequence: 20,
    step: "Allow certification assertion",
    contract: "AuthorityProfileRegistry",
    function: "setCapabilityGrant",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.CapabilityGrantSet"],
    valueRule: "zero",
  },
  {
    sequence: 21,
    step: "Allow listing creation",
    contract: "AuthorityProfileRegistry",
    function: "setCapabilityGrant",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.CapabilityGrantSet"],
    valueRule: "zero",
  },
  {
    sequence: 22,
    step: "Allow offer submission",
    contract: "AuthorityProfileRegistry",
    function: "setCapabilityGrant",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.CapabilityGrantSet"],
    valueRule: "zero",
  },
  {
    sequence: 23,
    step: "Allow logistics records",
    contract: "AuthorityProfileRegistry",
    function: "setCapabilityGrant",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.CapabilityGrantSet"],
    valueRule: "zero",
  },
  {
    sequence: 24,
    step: "Allow audit anchoring",
    contract: "AuthorityProfileRegistry",
    function: "setCapabilityGrant",
    signerRole: "governance",
    expectedEvents: ["AuthorityProfileRegistry.CapabilityGrantSet"],
    valueRule: "zero",
  },
  {
    sequence: 25,
    step: "Propose initial recorded ownership",
    contract: "BatteryOwnershipRegistry",
    function: "proposeInitialOwnership",
    signerRole: "registrar",
    expectedEvents: ["BatteryOwnershipRegistry.InitialOwnershipProposed"],
    valueRule: "zero",
  },
  {
    sequence: 26,
    step: "Accept initial recorded ownership",
    contract: "BatteryOwnershipRegistry",
    function: "acceptInitialOwnership",
    signerRole: "seller",
    expectedEvents: [
      "BatteryOwnershipRegistry.InitialOwnershipProposalClosed",
      "BatteryOwnershipRegistry.BatteryRegistered",
    ],
    valueRule: "zero",
  },
  {
    sequence: 27,
    step: "Commit attested diagnostic-evidence bundle",
    contract: "ProtectedBundleRegistry",
    function: "commitAttestedProtectedBundle",
    signerRole: "controller",
    expectedEvents: [
      "ProtectedBundleRegistry.ProtectedBundleCommitted",
      "ProtectedBundleRegistry.DomainAttestationConsumed",
    ],
    valueRule: "zero",
  },
  {
    sequence: 28,
    step: "Verify replica receipt for diagnostic-evidence",
    contract: "ProtectedBundleRegistry",
    function: "submitReplicaReceipt",
    signerRole: "replica_attester",
    expectedEvents: ["ProtectedBundleRegistry.ReplicaReceiptVerified"],
    valueRule: "zero",
  },
  {
    sequence: 29,
    step: "Promote diagnostic-evidence bundle to decision critical",
    contract: "ProtectedBundleRegistry",
    function: "promoteToDecisionCritical",
    signerRole: "controller",
    expectedEvents: ["ProtectedBundleRegistry.ProtectedBundlePromoted"],
    valueRule: "zero",
  },
  {
    sequence: 30,
    step: "Activate the diagnostic evidence claim",
    contract: "EvidenceRegistry",
    function: "activateEvidence",
    signerRole: "issuer",
    expectedEvents: ["EvidenceRegistry.EvidenceActivated"],
    valueRule: "zero",
  },
  {
    sequence: 31,
    step: "Commit attested verification-assertion bundle",
    contract: "ProtectedBundleRegistry",
    function: "commitAttestedProtectedBundle",
    signerRole: "controller",
    expectedEvents: [
      "ProtectedBundleRegistry.ProtectedBundleCommitted",
      "ProtectedBundleRegistry.DomainAttestationConsumed",
    ],
    valueRule: "zero",
  },
  {
    sequence: 32,
    step: "Verify replica receipt for verification-assertion",
    contract: "ProtectedBundleRegistry",
    function: "submitReplicaReceipt",
    signerRole: "replica_attester",
    expectedEvents: ["ProtectedBundleRegistry.ReplicaReceiptVerified"],
    valueRule: "zero",
  },
  {
    sequence: 33,
    step: "Promote verification-assertion bundle to decision critical",
    contract: "ProtectedBundleRegistry",
    function: "promoteToDecisionCritical",
    signerRole: "controller",
    expectedEvents: ["ProtectedBundleRegistry.ProtectedBundlePromoted"],
    valueRule: "zero",
  },
  {
    sequence: 34,
    step: "Create the independent certification assertion",
    contract: "EvidenceRegistry",
    function: "createVerificationAssertion",
    signerRole: "verifier",
    expectedEvents: ["EvidenceRegistry.VerificationAssertionCreated"],
    valueRule: "zero",
  },
  {
    sequence: 35,
    step: "Commit attested listing bundle",
    contract: "ProtectedBundleRegistry",
    function: "commitAttestedProtectedBundle",
    signerRole: "seller",
    expectedEvents: [
      "ProtectedBundleRegistry.ProtectedBundleCommitted",
      "ProtectedBundleRegistry.DomainAttestationConsumed",
    ],
    valueRule: "zero",
  },
  {
    sequence: 36,
    step: "Verify replica receipt for listing",
    contract: "ProtectedBundleRegistry",
    function: "submitReplicaReceipt",
    signerRole: "replica_attester",
    expectedEvents: ["ProtectedBundleRegistry.ReplicaReceiptVerified"],
    valueRule: "zero",
  },
  {
    sequence: 37,
    step: "Promote listing bundle to decision critical",
    contract: "ProtectedBundleRegistry",
    function: "promoteToDecisionCritical",
    signerRole: "seller",
    expectedEvents: ["ProtectedBundleRegistry.ProtectedBundlePromoted"],
    valueRule: "zero",
  },
  {
    sequence: 38,
    step: "Create the protected marketplace listing",
    contract: "Marketplace",
    function: "createListing",
    signerRole: "seller",
    expectedEvents: [
      "BatteryOwnershipRegistry.MarketplaceLockChanged",
      "DeploymentRegistry.AggregateOriginBound",
      "Marketplace.ListingCreated",
    ],
    valueRule: "zero",
  },
  {
    sequence: 39,
    step: "Submit the buyer offer",
    contract: "Marketplace",
    function: "submitOffer",
    signerRole: "buyer",
    expectedEvents: ["Marketplace.OfferSubmitted"],
    valueRule: "zero",
  },
  {
    sequence: 40,
    step: "Commit attested agreement bundle",
    contract: "ProtectedBundleRegistry",
    function: "commitAttestedProtectedBundle",
    signerRole: "seller",
    expectedEvents: [
      "ProtectedBundleRegistry.ProtectedBundleCommitted",
      "ProtectedBundleRegistry.DomainAttestationConsumed",
    ],
    valueRule: "zero",
  },
  {
    sequence: 41,
    step: "Verify replica receipt for agreement",
    contract: "ProtectedBundleRegistry",
    function: "submitReplicaReceipt",
    signerRole: "replica_attester",
    expectedEvents: ["ProtectedBundleRegistry.ReplicaReceiptVerified"],
    valueRule: "zero",
  },
  {
    sequence: 42,
    step: "Promote agreement bundle to decision critical",
    contract: "ProtectedBundleRegistry",
    function: "promoteToDecisionCritical",
    signerRole: "seller",
    expectedEvents: ["ProtectedBundleRegistry.ProtectedBundlePromoted"],
    valueRule: "zero",
  },
  {
    sequence: 43,
    step: "Select the offer and create the protected agreement",
    contract: "Marketplace",
    function: "selectOfferAndCreateAgreement",
    signerRole: "seller",
    expectedEvents: ["DeploymentRegistry.AggregateOriginBound", "Marketplace.AgreementCreated"],
    valueRule: "zero",
  },
  {
    sequence: 44,
    step: "Confirm buyer access to the agreement",
    contract: "Marketplace",
    function: "confirmAgreement",
    signerRole: "buyer",
    expectedEvents: ["Marketplace.AgreementStateChanged"],
    valueRule: "zero",
  },
  {
    sequence: 45,
    step: "Fund the agreement",
    contract: "Marketplace",
    function: "fundAgreement",
    signerRole: "buyer",
    expectedEvents: ["Marketplace.AgreementStateChanged"],
    valueRule: "purchase-amount",
  },
  {
    sequence: 46,
    step: "Commit attested dispatch bundle",
    contract: "ProtectedBundleRegistry",
    function: "commitAttestedProtectedBundle",
    signerRole: "logistics_provider",
    expectedEvents: [
      "ProtectedBundleRegistry.ProtectedBundleCommitted",
      "ProtectedBundleRegistry.DomainAttestationConsumed",
    ],
    valueRule: "zero",
  },
  {
    sequence: 47,
    step: "Verify replica receipt for dispatch",
    contract: "ProtectedBundleRegistry",
    function: "submitReplicaReceipt",
    signerRole: "replica_attester",
    expectedEvents: ["ProtectedBundleRegistry.ReplicaReceiptVerified"],
    valueRule: "zero",
  },
  {
    sequence: 48,
    step: "Promote dispatch bundle to decision critical",
    contract: "ProtectedBundleRegistry",
    function: "promoteToDecisionCritical",
    signerRole: "logistics_provider",
    expectedEvents: ["ProtectedBundleRegistry.ProtectedBundlePromoted"],
    valueRule: "zero",
  },
  {
    sequence: 49,
    step: "Commit attested delivery bundle",
    contract: "ProtectedBundleRegistry",
    function: "commitAttestedProtectedBundle",
    signerRole: "logistics_provider",
    expectedEvents: [
      "ProtectedBundleRegistry.ProtectedBundleCommitted",
      "ProtectedBundleRegistry.DomainAttestationConsumed",
    ],
    valueRule: "zero",
  },
  {
    sequence: 50,
    step: "Verify replica receipt for delivery",
    contract: "ProtectedBundleRegistry",
    function: "submitReplicaReceipt",
    signerRole: "replica_attester",
    expectedEvents: ["ProtectedBundleRegistry.ReplicaReceiptVerified"],
    valueRule: "zero",
  },
  {
    sequence: 51,
    step: "Promote delivery bundle to decision critical",
    contract: "ProtectedBundleRegistry",
    function: "promoteToDecisionCritical",
    signerRole: "logistics_provider",
    expectedEvents: ["ProtectedBundleRegistry.ProtectedBundlePromoted"],
    valueRule: "zero",
  },
  {
    sequence: 52,
    step: "Record dispatch",
    contract: "Marketplace",
    function: "recordDispatch",
    signerRole: "logistics_provider",
    expectedEvents: ["Marketplace.LogisticsRecorded", "Marketplace.AgreementStateChanged"],
    valueRule: "zero",
  },
  {
    sequence: 53,
    step: "Record delivery",
    contract: "Marketplace",
    function: "recordDelivery",
    signerRole: "logistics_provider",
    expectedEvents: ["Marketplace.LogisticsRecorded", "Marketplace.AgreementStateChanged"],
    valueRule: "zero",
  },
  {
    sequence: 54,
    step: "Accept delivery",
    contract: "Marketplace",
    function: "acceptDelivery",
    signerRole: "buyer",
    expectedEvents: ["Marketplace.AgreementStateChanged"],
    valueRule: "zero",
  },
  {
    sequence: 55,
    step: "Settle the accepted agreement",
    contract: "Marketplace",
    function: "settleAccepted",
    signerRole: "governance",
    expectedEvents: [
      "BatteryOwnershipRegistry.RecordedOwnershipTransferred",
      "BatteryOwnershipRegistry.MarketplaceLockChanged",
      "Marketplace.CreditCreated",
      "Marketplace.AgreementStateChanged",
    ],
    valueRule: "zero",
  },
  {
    sequence: 56,
    step: "Withdraw the seller credit",
    contract: "Marketplace",
    function: "withdrawCredits",
    signerRole: "seller",
    expectedEvents: ["Marketplace.CreditWithdrawn"],
    valueRule: "zero",
  },
  {
    sequence: 57,
    step: "Anchor the workflow audit batch",
    contract: "AuditAnchor",
    function: "anchorBatch",
    signerRole: "audit_anchor",
    expectedEvents: ["AuditAnchor.AuditBatchAnchored"],
    valueRule: "zero",
  },
]);
